apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: dgutierrez64/nodejs
        ports:
        - containerPort: 5000
